### ISSUE TITLE
Unable to swipe on Symptom Evaluation

### ISSUE THREAD

**Issue by yvonechau** [yvonechau/ConcussionAssessment2.0#29]
Build: Current Master

Bug: When swiping left or right within the Symptom Evaluation, app hangs

Suspected Problem: index within function pageViewController needs a check to see if it exists or not. Check for gesture? 

Passing Criteria: Swiping left or right does not affect the test.

**Comment by snavien** [comment]
Swiping should work, it works on the gray part of the page, please test and see if that fixes the problem
